apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-ratelimit-config
data:
  config.yaml: |
    domain: catalog-ratelimit
    descriptors:
      - key: header_match
        value: no_headermatch
        rate_limit:
          unit: MINUTE
          requests_per_unit: 1
