apiVersion: v1
kind: Service
metadata:
  name: echo
spec:
  clusterIP: 10.96.88.88
  ports:
  - name: http-echo
    port: 80
    targetPort: 8080
  selector:
    app: echo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
spec:
  replicas: 1
  template:
    metadata:
      name: echo
      labels:
        app: echo
    spec:
      nodeName: h1.baremental.meshbench-pg0.clemson.cloudlab.us
      containers:
      - image: xzhu0027/echo:in
        name: echoserver
  selector:
    matchLabels:
      app: echo
