apiVersion: v1
kind: Service
metadata:
  name: kubia
spec:
  clusterIP: 10.96.99.99
  ports:
  - name: tcp-kubia
    port: 80
    targetPort: 8080
  selector:
    app: kubia
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubia
spec:
  replicas: 1
  template:
    metadata:
      name: kubia
      labels:
        app: kubia
    spec:
      nodeName: h1.baremental.meshbench-pg0.clemson.cloudlab.us
      containers:
        - name: kubia
          image: luksa/kubia:latest
          ports:
          - containerPort: 8080
            protocol: TCP
  selector:
    matchLabels:
      app: kubia
