apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: geo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: geo-storage
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: profile-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: profile-storage
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rate-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rate-storage
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recommendation-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: recommendation-storage
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reservation-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: reservation-storage
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: user-storage
  resources:
    requests:
      storage: 1Gi
---