apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: hotel-lua-extension
spec:
  workloadSelector:
    labels:
      io.kompose.service: user
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        portNumber: 8086
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
            subFilter:
              name: "envoy.filters.http.router"
    patch:
      operation: INSERT_BEFORE
      value: 
       name: envoy.lua
       typed_config:
          "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
          inlineCode: |
            function envoy_on_request(request_handle)            
              os.execute("sleep " .. tonumber(0.00002))
            end          
            function envoy_on_response(response_handle)
            end

