apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: hotel-lua-extension
spec:
  workloadSelector:
    labels:
      io.kompose.service: frontend
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        portNumber: 5000
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
            subFilter:
              name: "envoy.filters.http.router"
    patch:
      operation: INSERT_BEFORE
      value: 
       name: envoy.lua
       typed_config:
          "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
          inlineCode: |
            function envoy_on_request(handle)
              handle:logWarn(" ============= envoy_on_request ============= ")
              local headers = handle:headers()
              handle:logWarn(authToken)
              handle:logWarn(" ============================================= ")
            end
            function envoy_on_response(handle)
              handle:logWarn(" ============= envoy_on_response ============= ")
              handle:headers():add("my-custom-header-response","my-header-value")
              handle:logWarn("Custom header has been added to respose")
              handle:logWarn(" ============================================= ")
            end
