apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.25.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: dns-media
  name: dns-media
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dns-media
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.25.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: dns-media
    spec:
      containers:
        - image: defreitas/dns-proxy-server
          name: dns-media
          resources: {}
          volumeMounts:
            - mountPath: /app/conf
              name: dns-media-claim0
            - mountPath: /var/run/docker.sock
              name: dns-media-claim1
            - mountPath: /etc/resolv.conf
              name: dns-media-claim2
      restartPolicy: Always
      volumes:
        - name: dns-media-claim0
          persistentVolumeClaim:
            claimName: dns-media-claim0
        - name: dns-media-claim1
          persistentVolumeClaim:
            claimName: dns-media-claim1
        - name: dns-media-claim2
          persistentVolumeClaim:
            claimName: dns-media-claim2
status: {}
