apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.25.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx-web-server
  name: nginx-web-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx-web-server
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.25.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: nginx-web-server
    spec:
      containers:
        - image: yg397/openresty-thrift:xenial
          name: nginx-web-server
          ports:
            - containerPort: 8080
          resources: {}
          volumeMounts:
            - mountPath: /usr/local/openresty/nginx/lua-scripts
              name: nginx-web-server-claim0
            - mountPath: /usr/local/openresty/nginx/conf/nginx.conf
              name: nginx-web-server-claim1
            - mountPath: /usr/local/openresty/nginx/jaeger-config.json
              name: nginx-web-server-claim2
            - mountPath: /gen-lua
              name: nginx-web-server-claim3
      hostname: nginx-thrift
      restartPolicy: Always
      volumes:
        - name: nginx-web-server-claim0
          persistentVolumeClaim:
            claimName: nginx-web-server-claim0
        - name: nginx-web-server-claim1
          persistentVolumeClaim:
            claimName: nginx-web-server-claim1
        - name: nginx-web-server-claim2
          persistentVolumeClaim:
            claimName: nginx-web-server-claim2
        - name: nginx-web-server-claim3
          persistentVolumeClaim:
            claimName: nginx-web-server-claim3
status: {}
