apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.25.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: review-storage-memcached
  name: review-storage-memcached
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: review-storage-memcached
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.25.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: review-storage-memcached
    spec:
      containers:
        - image: memcached
          name: review-storage-memcached
          ports:
            - containerPort: 11211
          resources: {}
      hostname: review-storage-memcached
      restartPolicy: Always
status: {}
