apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.25.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: review-storage-mongodb
  name: review-storage-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: review-storage-mongodb
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.25.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: review-storage-mongodb
    spec:
      containers:
        - image: mongo
          name: review-storage-mongodb
          resources: {}
      hostname: review-storage-mongodb
      restartPolicy: Always
status: {}
