apiVersion: v1
kind: ConfigMap
metadata:
  name: hotel-ratelimit-config
data:
  config.yaml: |
    domain: frontend-ratelimit
    descriptors:
      - key: header_match
        value: no_headermatch
        rate_limit:
          unit: MINUTE
          requests_per_unit: 100000
    domain: user-ratelimit
    descriptors:
      - key: header_match
        value: no_headermatch
        rate_limit:
          unit: MINUTE
          requests_per_unit: 100000
    domain: geo-ratelimit
    descriptors:
      - key: header_match
        value: no_headermatch
        rate_limit:
          unit: MINUTE
          requests_per_unit: 100000
    domain: profile-ratelimit
    descriptors:
      - key: header_match
        value: no_headermatch
        rate_limit:
          unit: MINUTE
          requests_per_unit: 100000
    domain: rate-ratelimit
    descriptors:
      - key: header_match
        value: no_headermatch
        rate_limit:
          unit: MINUTE
          requests_per_unit: 100000
    domain: recommendation-ratelimit
    descriptors:
      - key: header_match
        value: no_headermatch
        rate_limit:
          unit: MINUTE
          requests_per_unit: 100000
          requests_per_unit: 100000
    domain: reservation-ratelimit
    descriptors:
      - key: header_match
        value: no_headermatch
        rate_limit:
          unit: MINUTE
          requests_per_unit: 100000
    domain: search-ratelimit
    descriptors:
      - key: header_match
        value: no_headermatch
        rate_limit:
          unit: MINUTE
          requests_per_unit: 100000