---
apiVersion: v1
kind: Service
metadata:
  name: media-service
  labels:
    death-star-project: social-network
    app: media-service
  namespace: social-network
spec:
  ports:
    - name: tcp
      port: 19090
  selector:
    death-star-project: social-network
    app: media-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-service
  labels:
    death-star-project: social-network
    app: media-service
  namespace: social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: social-network
      app: media-service
  template:
    metadata:
      labels:
        # sidecar.istio.io/inject: "false"
        death-star-project: social-network
        app: media-service
      name: media-service
    spec:
      nodeName: h3.mesh.meshbench-pg0.clemson.cloudlab.us
      containers:
      - name: media-service
        image: bx33/social-network-microservices
        command: ["MediaService"]
        volumeMounts:
          - mountPath: /social-network-microservices/config/jaeger-config.yml
            subPath: jaeger-config.yml
            name: jaeger-conf-yaml
          - mountPath: /social-network-microservices/config/service-config.json
            subPath: service-config.json
            name: service-config-json
      restartPolicy: Always
      volumes:
        - name: jaeger-conf-yaml
          configMap:
            name: jaeger-config-yaml
        - name: service-config-json
          configMap:
            name: service-config-json
