---
apiVersion: v1
kind: Service
metadata:
  name: media-memcached
  labels:
    death-star-project: social-network
    app: media-memcached
  namespace: social-network
spec:
  ports:
    - name: tcp 
      port: 11211
  selector:
    death-star-project: social-network
    app: media-memcached
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-memcached
  labels:
    death-star-project: social-network
    app: media-memcached
  namespace: social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: social-network
      app: media-memcached
  template:
    metadata:
      labels:
        sidecar.istio.io/inject: "false"
        death-star-project: social-network
        app: media-memcached
      name: media-memcached
    spec:
      nodeName: h2.mesh.meshbench-pg0.clemson.cloudlab.us
      containers:
      - name: media-memcached
        image: memcached
      restartPolicy: Always
