---
apiVersion: v1
kind: Service
metadata:
  name: media-frontend
  labels:
    death-star-project: social-network
    app: media-frontend
  namespace: social-network
spec:
  type: ClusterIP
  ports:
    - name: tcp
      port: 18080
      targetPort: 18080
  selector:
    death-star-project: social-network
    app: media-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-frontend
  labels:
    death-star-project: social-network
    app: media-frontend
  namespace: social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: social-network
      app: media-frontend
  template:
    metadata:
      labels:
        sidecar.istio.io/inject: "false"
        death-star-project: social-network
        app: media-frontend
      name: media-frontend
    spec:
      nodeName: h2.mesh.meshbench-pg0.clemson.cloudlab.us
      containers:
      - name: media-frontend
        image: yg397/media-frontend:xenial
        ports:
        - containerPort: 18080
        volumeMounts:
        - mountPath: /usr/local/openresty/nginx/lua-scripts
          name: lua-conf
        - mountPath: /usr/local/openresty/nginx/conf/nginx.conf
          subPath: nginx.conf
          name: nginx-conf
        - mountPath: /usr/local/openresty/nginx/conf/jaeger-config.yml
          subPath: jaeger-config.yml
          name: jaeger-conf
      restartPolicy: Always
      volumes:
      - name: nginx-conf
        configMap:
          name: media-frontend-nginx
          items:
          - key: nginx.conf
            path: nginx.conf
      - name: lua-conf
        configMap:
          name: media-frontend-lua
      - name: jaeger-conf
        configMap:
          name: jaeger-config-yaml
