---
apiVersion: v1
kind: Service
metadata:
  name: media-mongodb
  labels:
    death-star-project: social-network
    app: media-mongodb
  namespace: social-network
spec:
  ports:
    - name: tcp 
      port: 27017
  selector:
    death-star-project: social-network
    app: media-mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-mongodb
  labels:
    death-star-project: social-network
    app: media-mongodb
  namespace: social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: social-network
      app: media-mongodb
  template:
    metadata:
      labels:
        sidecar.istio.io/inject: "false"
        death-star-project: social-network
        app: media-mongodb
      name: media-mongodb
    spec:
      nodeName: h2.mesh.meshbench-pg0.clemson.cloudlab.us
      containers:
      - name: media-mongodb
        image: mongo
        volumeMounts:
          - name: my-data
            mountPath: "/data/db"
      restartPolicy: Always
      volumes:
      - name: my-data
        emptyDir: {}
