---
apiVersion: v1
kind: Service
metadata:
  name: post-storage-mongodb
  labels:
    death-star-project: social-network
    app: post-storage-mongodb
  namespace: social-network
spec:
  ports:
  - name: tcp 
    port: 27017
  selector:
    death-star-project: social-network
    app: post-storage-mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-storage-mongodb
  labels:
    death-star-project: social-network
    app: post-storage-mongodb
  namespace: social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: social-network
      app: post-storage-mongodb
  template:
    metadata:
      labels:
        # sidecar.istio.io/inject: "false"
        death-star-project: social-network
        app: post-storage-mongodb
      name: post-storage-mongodb
    spec:
      nodeName: h3.mesh.meshbench-pg0.clemson.cloudlab.us
      containers:
      - name: post-storage-mongodb
        image: mongo
        volumeMounts:
          - name: my-data
            mountPath: "/data/db"
      restartPolicy: Always
      volumes:
      - name: my-data
        emptyDir: {}
