---
apiVersion: v1
kind: Service
metadata:
  name: social-graph-redis
  labels:
    death-star-project: social-network
    app: social-graph-redis
  namespace: social-network
spec:
  ports:
    - name: tcp
      port: 6379
  selector:
    death-star-project: social-network
    app: social-graph-redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: social-graph-redis
  labels:
    death-star-project: social-network
    app: social-graph-redis
  namespace: social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: social-network
      app: social-graph-redis
  template:
    metadata:
      labels:
        sidecar.istio.io/inject: "false"
        death-star-project: social-network
        app: social-graph-redis
      name: social-graph-redis
    spec:
      nodeName: h2.mesh.meshbench-pg0.clemson.cloudlab.us
      containers:
      - name: social-graph-redis
        image: redis
      restartPolicy: Always
