---
apiVersion: v1
kind: Service
metadata:
  name: url-shorten-memcached
  labels:
    death-star-project: social-network
    app: url-shorten-memcached
  namespace: social-network
spec:
  ports:
    - name: tcp 
      port: 11211
  selector:
    death-star-project: social-network
    app: url-shorten-memcached
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shorten-memcached
  labels:
    death-star-project: social-network
    app: url-shorten-memcached
  namespace: social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: social-network
      app: url-shorten-memcached
  template:
    metadata:
      labels: 
        sidecar.istio.io/inject: "false"
        death-star-project: social-network
        app: url-shorten-memcached
      name: url-shorten-memcached
    spec: 
      nodeName: h2.mesh.meshbench-pg0.clemson.cloudlab.us
      containers:
      - name: url-shorten-memcached
        image: memcached
      restartPolicy: Always
