---
apiVersion: v1
kind: Service
metadata:
  name: user-timeline-mongodb
  labels:
    death-star-project: social-network
    app: user-timeline-mongodb
  namespace: social-network
spec:
  ports:
    - name: tcp
      port: 27017
  selector:
    death-star-project: social-network
    app: user-timeline-mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-timeline-mongodb
  labels:
    death-star-project: social-network
    app: user-timeline-mongodb
  namespace: social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: social-network
      app: user-timeline-mongodb
  template:
    metadata:
      labels:
        # sidecar.istio.io/inject: "false"
        death-star-project: social-network
        app: user-timeline-mongodb
      name: user-timeline-mongodb
    spec:
      nodeName: h3.mesh.meshbench-pg0.clemson.cloudlab.us
      containers:
      - name: user-timeline-mongodb
        image: mongo
        volumeMounts:
          - name: my-data
            mountPath: "/data/db"
      restartPolicy: Always
      volumes:
      - name: my-data
        emptyDir: {}
