apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.25.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: cast-info-memcached
  name: cast-info-memcached
spec:
  ports:
    - name: "11219"
      port: 11219
      targetPort: 11211
  selector:
    io.kompose.service: cast-info-memcached
status:
  loadBalancer: {}
