apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.25.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: movie-review-mongodb
  name: movie-review-mongodb
spec:
  ports:
    - name: "27022"
      port: 27022
      targetPort: 27017
  selector:
    io.kompose.service: movie-review-mongodb
status:
  loadBalancer: {}
