apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.25.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: movie-review-service
  name: movie-review-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: movie-review-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.25.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: movie-review-service
    spec:
      containers:
        - command:
            - MovieReviewService
          image: yg397/media-microservices
          name: movie-review-service
          resources: {}
      hostname: movie-review-service
      restartPolicy: Always
status: {}
