apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.25.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: user-review-service
  name: user-review-service
spec:
  ports:
    - name: "10008"
      port: 10008
      targetPort: 9090
  selector:
    io.kompose.service: user-review-service
status:
  loadBalancer: {}
